### ISSUE TITLE
Lint-test failed for louis-crawler

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/louis-crawler-legacy#8]
https://github.com/ai-cfia/louis-crawler/actions/runs/6340529474
unittest failed in this run

**Comment by rngadam** [comment]
@redat97 need a more in-depth assessment when reporting these failures.

AFAIK this is caused by a connection to the database

```
    connection = psycopg.connect(
                 ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect
    raise ex.with_traceback(None)
psycopg.OperationalError: connection failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

AFAIK, you need to ensure that the test suite is pointing to a working db (our azure flexible postgresql database)

**Comment by rngadam** [comment]
ruff linting fixes applied and database configured, getting failures here that point to ailab-db functions not having been updated with their corresponding schema changes:

```
======================================================================
ERROR: test_fetch_crawl_ids_without_chunk (test_db.TestDB.test_fetch_crawl_ids_without_chunk)
sample test to check if fetch_crawl_ids_without_chunk works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/louis-crawler/tests/test_db.py", line 53, in test_fetch_crawl_ids_without_chunk
    crawl_ids = crawler.fetch_crawl_ids_without_chunk(cursor)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/louis-crawler/src/ailab-db/ailab/db/crawler/__init__.py", line 170, in fetch_crawl_ids_without_chunk
    cursor.execute(query)
  File "/home/vscode/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column html_content_to_chunk.html_content_md5hash does not exist
LINE 4:          ON crawl.md5hash = html_content_to_chunk.html_conte...
                                    ^

======================================================================
ERROR: test_store_chunk_item2 (test_db.TestDB.test_store_chunk_item2)
sample test to check if store_chunk_item works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/louis-crawler/tests/test_db.py", line 63, in test_store_chunk_item2
    stored_chunk = crawler.store_chunk_item(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/louis-crawler/src/ailab-db/ailab/db/crawler/__init__.py", line 82, in store_chunk_item
    cursor.execute(
  File "/home/vscode/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column "html_content_md5hash" of relation "html_content_to_chunk" does not exist
LINE 2:             INSERT INTO html_content_to_chunk (html_content_...
                                                       ^

======================================================================
ERROR: test_store_chunk_page1581548517693 (test_db.TestDB.test_store_chunk_page1581548517693)
sample test to check if store_chunk_item works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/louis-crawler/tests/test_db.py", line 72, in test_store_chunk_page1581548517693
    stored_chunk = crawler.store_chunk_item(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/louis-crawler/src/ailab-db/ailab/db/crawler/__init__.py", line 82, in store_chunk_item
    cursor.execute(
  File "/home/vscode/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column "html_content_md5hash" of relation "html_content_to_chunk" does not exist
LINE 2:             INSERT INTO html_content_to_chunk (html_content_...
                                                       ^

======================================================================
ERROR: test_store_crawl_chunk_embedding_item (test_db.TestDB.test_store_crawl_chunk_embedding_item)
sample test to check if three steps storage works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/louis-crawler/src/ailab-db/ailab/db/crawler/__init__.py", line 121, in store_crawl_item
    cursor.execute(
  File "/home/vscode/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.ForeignKeyViolation: insert or update on table "crawl" violates foreign key constraint "crawl_to_html_content_md5hash_fkey"
DETAIL:  Key (md5hash)=(7fbe968edbc7a1e82c817bd85b264c19) is not present in table "html_content".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/louis-crawler/tests/test_db.py", line 25, in test_store_crawl_chunk_embedding_item
    crawl_item = crawler.store_crawl_item(cursor, {
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/louis-crawler/src/ailab-db/ailab/db/crawler/__init__.py", line 132, in store_crawl_item
    raise db.DBError("Error storing crawl item for %s" % item['url']) from e
ailab.db.DBError: Error storing crawl item for https://inspection.canada.ca/a-propos-de-l-acia/contactez-nous/fra/1546627816321/1546627838025

======================================================================
ERROR: test_storing_chunk_item_that_already_exists_has_no_effect (test_db.TestDB.test_storing_chunk_item_that_already_exists_has_no_effect)
sample test to check if store_chunk_item works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/louis-crawler/tests/test_db.py", line 104, in test_storing_chunk_item_that_already_exists_has_no_effect
    chunk_item_first_insert = crawler.store_chunk_item(cursor, item)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/louis-crawler/src/ailab-db/ailab/db/crawler/__init__.py", line 82, in store_chunk_item
    cursor.execute(
  File "/home/vscode/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column "html_content_md5hash" of relation "html_content_to_chunk" does not exist
LINE 2:             INSERT INTO html_content_to_chunk (html_content_...
                                                       ^

======================================================================
ERROR: test_spider1 (test_integration.SpidersTests.test_spider1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/louis-crawler/tests/test_integration.py", line 27, in test_spider1
    _requests = list(crawler.spider.start_requests())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/louis-crawler/louis/crawler/spiders/russell.py", line 22, in start_requests
    crawl_ids = fetch_crawl_ids_without_chunk(cursor)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/louis-crawler/src/ailab-db/ailab/db/crawler/__init__.py", line 170, in fetch_crawl_ids_without_chunk
    cursor.execute(query)
  File "/home/vscode/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

----------------------------------------------------------------------
Ran 26 tests in 2.768s

FAILED (errors=6)
Finished running tests!
```

**Comment by rngadam** [comment]
need  to test and fix ailab.crawler functions @melanie-fressard
